spring.application.name=immo-manager

# Configuration MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/immo_manager?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port du serveur
server.port=8080
